### ISSUE TITLE
Is the label going to be publicly available?

### ISSUE THREAD

**Issue by lihaoliu-cambridge** [MASILab/SLANTbrainSeg#1]
Is the label going to be publicly available?

**Comment by yuankaihuo** [comment]
Most of OASIS labels are avilable from our MICCAI 2012 challenge
Thanks

**Comment by lihaoliu-cambridge** [comment]
Thanks for the reply. I found it. However, how did you download data Colin27 and CANDI13 from the neuromorphometrics inc . I cannot find a download link from its website.

**Comment by yuankaihuo** [comment]
My pleasure. You can buy from the company and they are not free.

**Comment by ZYX-MLer** [comment]
Dear yuankaihuo  

in your paper, you use 50 oasis scans each scans has 133 labels,  but miccai2012 only has 35 scans, and each scan has 134 labels, how can i get the other scans? and can you tell me the name in your training and testing set of oasis dataset? thank you.

**Comment by yuankaihuo** [comment]
We brought the remaining from the
neuromorphometrics inc. which have not been made free avilable. We train
use 45 OASIS scans, which means all 35 have been used in training. Thanks

**Comment by yuankaihuo** [comment]
35 in 45 training OASIS in the paper are free public available from MICCAI 2012 multi-atlas challenge. The remaining OASIS, CANDI, and Colin27 are not free, but can be purchased from neuromorphometrics inc.

**Comment by Qinka** [comment]
I can not find any label of OASIS when searching it on the Internet. Is that unavailable since 2019?
