### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by yuchen-xu** [MASILab/SLANTbrainSeg#10]
Hello,

I am trying to do a trial run of the pipeline following the steps given in "Quick Start." In the last step, I encountered the following error:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: initialization error\\\\n\\\"\"": unknown.
`

Output from docker pull:

`deep_brain_seg_v1_0_0: Pulling from vuiiscci/slant
Digest: sha256:7344b896423292c6bac0b3b1f82321672f4bedc49bddb1a388edb12367f5f8b5
Status: Image is up to date for vuiiscci/slant:deep_brain_seg_v1_0_0
`

I am wondering how I could get this to work. Thank you!

**Comment by yuankaihuo** [comment]
The current docker has been tested on both windows and Ubuntu. We haven't seen this error. Can you provide more details that when did you get the errors. For example, the OS, CPU/GPU docker, which stage is this error, log file? Thanks

**Comment by yuchen-xu** [comment]
It's Ubuntu on masi-12, I think it may be a GPU but I am not sure. Please see the attached screenshot for details - the last step didn't run at all, only giving the error message.
![Screen Shot 2020-05-24 at 18 23 22](https://user-images.githubusercontent.com/43591643/83344756-0e50ca00-a2d9-11ea-9a45-9479125d460f.png)
