### ISSUE TITLE
Not using GPU

### ISSUE THREAD

**Issue by AkhilaPerumalla123** [MASILab/SLANTbrainSeg#12]
Hi I am running this docker image on CUDA 11  machine.
I am able to see GPU information by doing nvidia-smi inside the docker.
But when running inference it is using CPU not GPU. Can someone help me to resolve the issue?

Thanks in Advance.

**Comment by rgbayrak** [comment]
I am having the same issue. @AkhilaPerumalla123 have you figured this out?

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
