### ISSUE TITLE
training

### ISSUE THREAD

**Issue by liamirpy** [MASILab/SLANTbrainSeg#15]
Hi
When I use CPU I get this :

/extra/python/torchsrc/trainer.py:192: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.

and there is no progressing .....

**Comment by jan-brabec** [comment]
Same problem here, I am copy-pasting the whole message for better debugging, it appears multiple times, the only thing that changes is the identification of the process that is killed (i.e. here 82 but it can be different number):

> Test:   0%|                                               | 0/1 [00:00<?, ?it/s]/extra/python/torchsrc/trainer.py:192: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.                                 | 0/1 [00:00<?, ?it/s]
>   data, target = Variable(data,volatile=True), Variable(target,volatile=True)
> /OUTPUTS/test_volume/working_dir/test_all_pieces.sh: line 3:    82 Killed                  /pythondir/miniconda/bin/python /extra/python/test.py --piece=1_1_3 --model_dir=/extra/model_dir --test_img_dir=/OUTPUTS/test_volume/working_dir/deep_learning --out_dir=/OUTPUTS/test_volume/working_dir/all_piece
> /pythondir/miniconda/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Namespace(model_dir='/extra/model_dir', out_dir='/OUTPUTS/test_volume/working_dir/all_piece', piece='1_2_1', test_img_dir='/OUTPUTS/test_volume/working_dir/deep_learning', used_epoch=27)
> using CPU with one thread

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.

**Comment by mukhsadr** [comment]
@jan-brabec 
Hi,

I'm encountering a similar issue where the process gets killed during the training phase at epoch 27. Here are the details:
``` /OUTPUTS/test_volume/working_dir/test_all_pieces.sh: line 4: 146 Killed /pythondir/miniconda/bin/python /extra/python/test.py --piece=1_2_1 --model_dir=/extra/model_dir --test_img_dir=/OUTPUTS/test_volume/working_dir/deep_learning --out_dir=/OUTPUTS/test_volume/working_dir/all_piece /pythondir/miniconda/lib/python2.7/site-packages/h5py/init.py:36:```

I've tried increasing Docker resources and updating the code to replace `volatile=True` with `with torch.no_grad():`, but the issue persists. Any help or suggestions would be greatly appreciated!

Thank you!
