### ISSUE TITLE
Questions about the dataset you used for fine tuning

### ISSUE THREAD

**Issue by penguin1109** [MASILab/SLANTbrainSeg#16]
Hello, while working on a computer vision task to classify parkinson diseases, I found that a more accurate brain mri segmentation mask was necessary.

I originally relied on the fastsurfer labels, but it did not fulfill my needs. Meanwhile, I found your work and the results were awesome. 

If I am not misunderstood, the OASIS dataset you ussd seems to be OASIS1. I wanted to see how the ground truth masks, but only the mri images were available, not the 133 class labeled masks you seemed to use.

If possible, could you tell me where I can find the segment label masks you used for fine tuning??

THANKS FOR YOUR AMAZING PAPER.
I'll be waiting for your response.

Thnaks again.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
