### ISSUE TITLE
training list

### ISSUE THREAD

**Issue by BorisMansencal** [MASILab/SLANTbrainSeg#2]
Hello,

Thanks a lot for this very interesting paper and the available code.

We would like to reproduce your experiments on the OASIS dataset.
Could you provide the list of the 45 MRI scans that you used for training ?

Thanks,
Boris.

**Comment by yuankaihuo** [comment]
Dear Boris
I have updated the readme file, which provides 45 MRI scans with OASIS#.
Have fun. 
Thanks!
Yuankai
