### ISSUE TITLE
Something is strange

### ISSUE THREAD

**Issue by zheng-xing** [MASILab/SLANTbrainSeg#4]
Hi Yuankai,

Thanks for open source this excellent work. In use of the software, I found the following warning messages. But visually checking the result, it looks OK to me. Can you let me know which part of the program gives this warning and what criteria does the program to judge whether the segmentation is strange or not? Thanks very much. 

-> Saving Label Volume Information
Output Text File: /OUTPUTS/FinalVolTxt/IXI232-IOP-0898-MRA_label_volumes.txt
Something is strange. Loading it untouched: /OUTPUTS/FinalResult/IXI232-IOP-0898-MRA_seg.nii.gz
The resulting nii file CANNOT be trusted

**Comment by yuankaihuo** [comment]
This is the very last steps in the pipeline, which will count the number of voxels of each region. You can refer to [https://github.com/MASILab/SLANTbrainSeg/blob/master/matlab/save_txt_file.m](https://github.com/MASILab/SLANTbrainSeg/blob/master/matlab/save_txt_file.m)

This warning is from the (load_nii.m and load_untouch_nii.m) matlab Tools for NIfTI and ANALYZE image toolbox (https://www.mathworks.com/matlabcentral/fileexchange/8797-tools-for-nifti-and-analyze-image). We used this toolbox to read header information of nifti volumes. If the toolbox thinks the header is weird, they will give this warning. 

I think your results should be fine as it is a warning. If you really want to make sure your header is valid, you can recalculate the volumes using python NiBabel toolbox and double-check.

Thanks!

**Comment by zheng-xing** [comment]
> This is the very last steps in the pipeline, which will count the number of voxels of each region. You can refer to https://github.com/MASILab/SLANTbrainSeg/blob/master/matlab/save_txt_file.m
> 
> This warning is from the (load_nii.m and load_untouch_nii.m) matlab Tools for NIfTI and ANALYZE image toolbox (https://www.mathworks.com/matlabcentral/fileexchange/8797-tools-for-nifti-and-analyze-image). We used this toolbox to read header information of nifti volumes. If the toolbox thinks the header is weird, they will give this warning.
> 
> I think your results should be fine as it is a warning. If you really want to make sure your header is valid, you can recalculate the volumes using python NiBabel toolbox and double-check.
> 
> Thanks!

Thanks for your detailed instructive reply. I really appropriate it.
