### ISSUE TITLE
Aivalable model training scans number ?

### ISSUE THREAD

**Issue by BorisMansencal** [MASILab/SLANTbrainSeg#5]
Hello,

How many training scans were used for the SLANT-27 model available in the docker image ? 
Is it "SLANT-27 trained with 45 scans" or "SLANT-27 trained with 5111 scans and fine-tuned with 45 scans" ?

Thank you,
Boris.

**Comment by yuankaihuo** [comment]
Thanks for your question.
SLANT-27 is trained by 5111 scans and fine-tuned by 45 scans.

**Comment by BorisMansencal** [comment]
Thanks. 
Would it be possible to provide the code you used to compute the Dice similarity coefficient (DSC) values in your papers ?
We are trying to reproduce your results and it seems that we compute the Dice differently as we get slightly different results.

**Comment by BorisMansencal** [comment]
I will try to be more specific.

We are trying to reproduce the Dice similarity coefficient (DSC) values presented in your SLANT papers. In particular, in your MICCA 2018 paper, Table 1, you get a mean DSC of **0.776** on the 5 test images from the OASIS dataset ( native_1120_3.nii.gz, native_1127_3.nii.gz, native_OAS1_0111_MR1.nii.gz, native_OAS1_0353_MR1.nii.gz, native_OAS1_0379_MR1.nii.gz )

We computed the segmentation of these five images with the available SLANT docker image and use this code https://gist.github.com/BorisMansencal/35ef825d56abcc57f55128db66490260 to compute the DSC. We only get a DSC of **0.75896**.

We would like to understand where this difference comes from.

Could you share the code you used to compute your DSC values ? Or have a look at our code ?

Thanks,
Boris.

**Comment by yuankaihuo** [comment]
Could you please send me your results nifti files. I am more than happy to evaluate it. My email is yuankai.huo@vanderbilt.edu 
I just sent my results and dice code to your email boris.mansencal@labri.fr    
Thanks!
> Thanks.
> Would it be possible to provide the code you used to compute the Dice similarity coefficient (DSC) values in your papers ?
> We are trying to reproduce your results and it seems that we compute the Dice differently as we get slightly different results.

**Comment by ZYX-MLer** [comment]
Hello
I meet the same problem as BorisMansencal, can you sent me a copy of your result and dice code too? 
Thanks.
