### ISSUE TITLE
Multi Atlas Appearance Model

### ISSUE THREAD

**Issue by saikat-roy** [MASILab/SLANTbrainSeg#7]
I am trying to train a SLANT-27 model by using your code and I have a question about the "Multi Atlas Appearance Model" that you have used in the preprocessing pipeline of your code. The paper mentions this as a "pretrained regression model from all training atlases on “sorted intensity” in MNI 305 space". Would it be possible for you to share the code that was used to train this model so that we can recreate the same on our dataset (and also the pretrained model if possible)?

Or if I have misunderstood something and the code to do this is present in the SLANT repository, could you point me to where it might be? I appreciate any help that you are able to provide.

**Comment by yuankaihuo** [comment]
All my preprocessing code is in
https://github.com/MASILab/SLANTbrainSeg/tree/master/matlab
You can start from
https://github.com/MASILab/SLANTbrainSeg/blob/master/matlab/preproc_pipline.m
The pretrained regression model is "atlas_model.mat", which is included in the Docker.
Thanks

**Comment by saikat-roy** [comment]
Thank you very much.
