### ISSUE TITLE
Is the UNet3D file the correct final version of the file?

### ISSUE THREAD

**Issue by saikat-roy** [MASILab/SLANTbrainSeg#8]
Hi. With reference to the file, https://github.com/MASILab/SLANTbrainSeg/blob/master/python/torchsrc/models/Unet3D.py 

can you confirm that that is the actual model file used in the published version of your work? I ask due to some differences noticed between the original UNet3d architecture and the one available in the url provided above.

**Comment by yuankaihuo** [comment]
This Unet3D in our Github is the version we used. 
Thanks

**Comment by saikat-roy** [comment]
Thank you for the confirmation.
