### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ilyanelken** [MASILab/SLANTbrainSeg#9]
Hello,

First of all thanks for providing the code and very good and detailed instructions for using it.
I wonder if there is a version that supports Windows os?

Thanks,
Ilya

**Comment by yuankaihuo** [comment]
The CPU version should already support windows as my friend run it on windows. The GPU version might work if you figure out how to do install nvidia-docker on windows.

**Comment by ilyanelken** [comment]
I see.  Also should win machine have 50 GB of RAM (from what I see in README.md)?

**Comment by yuankaihuo** [comment]
50G is based on our experience, yes. Thanks

**Comment by ilyanelken** [comment]
I understand. Thanks!
